### PR TITLE
Changes to version behaviour

### PR DESCRIPTION
**Pull request by tian2992**
Fixes for #53 and #49 
adds a new flag for --newversion and changes the default behaviour of --version to continue latest existing one by default.

### CODE REVIEW

**Comment by tian2992** [comment]
still needs more work, as it can sometimes miss existing versions

**Comment by odscjames** [comment]
@tian2992, Can you clarify the behaviour here, so who ever code reviews is clear what they are looking for?

- If no flag passed, ????
- If --newversion passed, make a new version?
- If --version passed with nothing, load last version?
- If --version passed with a string, load that specific version, and if that version doesn't exist, error?

@jpmckinney, I'm puzzled by the branch being deleted, can you clarify?

**Comment by jpmckinney** [comment]
The PR was approved and merged to master, and therefore deleted, per these practices: http://ocds-standard-development-handbook.readthedocs.io/en/latest/github/branch_management/#pruning-branches

Was there a reason to keep the branch?

**Comment by odscjames** [comment]
@jpmckinney It was merged - I'm sorry! The comment about it needing more work confused me. It should be deleted then.

@tian2992 I have moved the comment about it sometimes missing existing versions to a new issue just to make sure it isn't forgotten - https://github.com/open-contracting/ocdsdata/issues/69 Also, now i read the code the options are clear.

**Pull request merged**
