### PR TITLE
Don't error if no database when trying to do an operation that does not require the database

### PR DESCRIPTION
**Pull request by odscjames**
https://github.com/open-contracting/ocdsdata/issues/171

### CODE REVIEW

**Comment by odscjames** [comment]
Marking WIP because I'm not sure I like the init() function thing.

Maybe it should be a class instead? But then you have to have something to track getting a singleton instance of it, or pass round a reference to it .... Also, you'd have to deal with the fact we already have a class - add_file

**Comment by jpmckinney** [comment]
Django follows the pattern of a [`setup() method](https://github.com/django/django/blob/master/django/__init__.py) like your `init` method.

However, instead of calling `init()` everywhere, it just lets code fail if `setup` should have been called. How about doing things that way?

**Comment by odscjames** [comment]
Quick Q before a meeting:

>  it just lets code fail

Does it do any check at all (eg "if setup not called print nice error message, die"), or does the user just get a stack trace from elsewhere in the code?

I'm not sure I'm totally happy with that, but I'm happy to do that for now so we can merge this in - it's an important fix.

**Comment by jpmckinney** [comment]
It can fail with different errors from different parts of the code, depending on where the failure occurred. Django's `setup()` loads apps, so it can fail with `AppRegistryNotReady`. It also reads configurations, so it can fail with `ImproperlyConfigured`.

Here's a database example of `ImproperlyConfigured`: https://github.com/django/django/blob/master/django/db/backends/postgresql/base.py

If (I haven't checked) the methods that have `init()` as a prerequisite are only expected to be called internally, then having an unhelpful stack trace is not so bad.

If we prefer, we can change `engine` from a global variable to a memoized/singleton method. I don't like putting `init()` in all methods, because I don't think it's those methods' responsibility to setup the engine.

**Comment by kindly** [comment]
@odscjames  not sure about this either. Stylistically I would prefer a `@needs_database` decorator for the functions, instead of all those `init()` calls. However, even that is not great. 

I think I prefer something like @jpmckinney second option.  
I would probably make a function called `get_engine()` to use in place of all uses of `engine` that would return the global `engine` or create it then return it if it had not been made yet.  The downside of this is that `engine` is used a lot and would be a lot of changes.

**Comment by odscjames** [comment]
Let's do a `get_engine()` thing - I'll try and pick this up soon.

**Comment by odscjames** [comment]
Ready for review!

**Pull request merged**
