### PR TITLE
Checks

### PR DESCRIPTION
**Pull request by yolile**
WIP doing the pull request so that others can work on the command line

### CODE REVIEW

**Comment by odscjames** [comment]
Sorry @yolile for creating merge conflicts! :-(

The database structure has changed. It looks like it doesn't affect the new table - it will just have to be merged into database.py again.

And we enabled pep8 standards checking, so this code has to be checked with that.

**Comment by odscjames** [comment]
Hello @yolile! I have some time for the ETL tool again so have been making sure I understand what's happening with this.  Sorry for delay!

So as I'm new to this; can I check I understand the aim of this?

So this gets every version of every extension, and creates a new standard schema by merging the normal schema and the extension together (and any dependencies), and then stores that in the database?

So this would be used by calling get_all_extensions() and then the result is the schema table has one row per version of the extension?

I'm guessing the schema table is used for some other checks later?

One thing I might request is that this is moved to a different file than checks.py  - that file is now used for running cove checks against data in the database, so to avoid conflicts and keep separate functions separate could this be in a different file? (Sorry - I think what happened is this file was edited for 2 different purposes at the same time!)

Also I'm trying to merge #78 - that adds migrations to the database so the new table will have to be in that. Sorry - maybe it's better to start a new branch after that merge and pick the bits you want!

**Comment by odscjames** [comment]
This was discussed at Montreal Aug and a new plan was agreed.

See #189 for more.

**Comment by odscjames** [comment]
ps. Don't delete the branch - when doing #168 people will want to refer to it.

**Comment by jpmckinney** [comment]
@odscjames Can we delete this branch now?

**Comment by jpmckinney** [comment]
@odscjames Pinging again.

**Pull request closed without merging**
