### PR TITLE
Don't break if there's a newline at the end of ~/.pgpass

### PR DESCRIPTION
**Pull request by robredpath**

### CODE REVIEW

**Comment by robredpath** [comment]
@tian2992 good point, but shouldn't be - this fixes a specific issue I came across with template generation

**Comment by robredpath** [comment]
This isn't a complete implementation of support for .pgpass files, it's just enough to get by on the server. We could definitely use pgpasslib - https://pgpasslib.readthedocs.io/en/latest/ - to support more complex .pgpass files. 

My intent in using .pgpass was to avoid people having to maintain multiple copies of credentials between running ocdsdata-cli and making a local connection to the database. If that's not important, then I'm happy for us to have a separate config file.

**Comment by odscjames** [comment]
Personally I don't think that use case is enough to justify the possible confusion when one user account is being used for many projects. I'd vote for a separate config file.

Also, if my comment about multiple lines in .pgpass files is right - and I'm pretty sure it is (?) - then we in effect have buggy code in master branch now, and I'd argue that should be fixed sooner rather than later.

**Comment by robredpath** [comment]
> Personally I don't think that use case is enough to justify the possible confusion when one user account is being used for many projects. I'd vote for a separate config file.

I'm not sure where the confusion would come from - the usual way that .pgpass files are used (as I understand it) is that they provide a password lookup when the other details are specified. So, this is the most Postgres-ey way of storing credentials. 

> Also, if my comment about multiple lines in .pgpass files is right - and I'm pretty sure it is (?) - then we in effect have buggy code in master branch now, and I'd argue that should be fixed sooner rather than later

Fair point.

**Comment by odscjames** [comment]
> is that they provide a password lookup when the other details are specified.

Exactly - WHEN the other details are specified.

So eg, if you run

    pg_dump -U user2 db2

And you have a .pg_pass file with

    localhost:user1:db1:pass1
    localhost:user2:db2:pass2
    localhost:user3:db3:pass3    

Then pg_dump will look up the .pg_pass file, using localhost/user2/db2 to get the correct password pass2

But that's not how we are using it - unless I've miss-understood this - we are just opening the .pgpass and taking all the settings from there. So not only are we re-using a config file that other programmes use, we're using it wrongly. It's meant to be used for looking up the password when the other details are known, we're using it to look up all the details.


ps. Yes, you can have many lines: https://www.postgresql.org/docs/9.4/static/libpq-pgpass.html

**Comment by robredpath** [comment]
@odscjames yup, I've opened #64 as I've misunderstood what .pgpass files do

**Pull request merged**
